### ISSUE TITLE
Ingress rules through Network Policies are not working

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/firewall-policy-controller#3]
I think, ingress rules of network policies do never get created because of the following if-condition in the code:

```golang
if np.ObjectMeta.Namespace != "" {
	return nil
}
```
https://github.com/metal-stack/firewall-policy-controller/blob/master/pkg/controller/rules.go#L115-L117

It is actually not possible to set `""` for this resource as it is a namespaced property.

**Comment by majst01** [comment]
Should be solved with the new firewall-controller, please reopen if still present
